set_property PACKAGE_PIN E3  [get_ports clk];     set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.00 [get_ports clk]
set_property PACKAGE_PIN N17 [get_ports rst];     set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN M18 [get_ports btn_ped]; set_property IOSTANDARD LVCMOS33 [get_ports btn_ped]
set_property PACKAGE_PIN H17 [get_ports ns_red];  set_property IOSTANDARD LVCMOS33 [get_ports ns_red]
set_property PACKAGE_PIN K15 [get_ports ns_yellow]; set_property IOSTANDARD LVCMOS33 [get_ports ns_yellow]
set_property PACKAGE_PIN J13 [get_ports ns_green];  set_property IOSTANDARD LVCMOS33 [get_ports ns_green]
set_property PACKAGE_PIN N14 [get_ports ew_red];    set_property IOSTANDARD LVCMOS33 [get_ports ew_red]
set_property PACKAGE_PIN R18 [get_ports ew_yellow]; set_property IOSTANDARD LVCMOS33 [get_ports ew_yellow]
set_property PACKAGE_PIN V17 [get_ports ew_green];  set_property IOSTANDARD LVCMOS33 [get_ports ew_green]
set_property PACKAGE_PIN U17 [get_ports ped_wait];  set_property IOSTANDARD LVCMOS33 [get_ports ped_wait]
set_property PACKAGE_PIN U16 [get_ports ped_walk];  set_property IOSTANDARD LVCMOS33 [get_ports ped_walk]
set_property PACKAGE_PIN V16 [get_ports req_led];   set_property IOSTANDARD LVCMOS33 [get_ports req_led]